// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: buffers.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendBuffer = `-- name: AppendBuffer :exec
UPDATE ops.buffers
SET entries = entries || $2::jsonb,
    token_count = token_count + $3
WHERE id = $1
`

type AppendBufferParams struct {
	ID         uuid.UUID   `json:"id"`
	Column2    []byte      `json:"column_2"`
	TokenCount pgtype.Int4 `json:"token_count"`
}

func (q *Queries) AppendBuffer(ctx context.Context, arg AppendBufferParams) error {
	_, err := q.db.Exec(ctx, appendBuffer, arg.ID, arg.Column2, arg.TokenCount)
	return err
}

const createBuffer = `-- name: CreateBuffer :exec
INSERT INTO ops.buffers (
    id, tenant_id, user_id, source, entries,
    token_count, flush_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateBufferParams struct {
	ID         uuid.UUID          `json:"id"`
	TenantID   uuid.UUID          `json:"tenant_id"`
	UserID     uuid.UUID          `json:"user_id"`
	Source     string             `json:"source"`
	Entries    []byte             `json:"entries"`
	TokenCount pgtype.Int4        `json:"token_count"`
	FlushAt    pgtype.Timestamptz `json:"flush_at"`
}

func (q *Queries) CreateBuffer(ctx context.Context, arg CreateBufferParams) error {
	_, err := q.db.Exec(ctx, createBuffer,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Source,
		arg.Entries,
		arg.TokenCount,
		arg.FlushAt,
	)
	return err
}

const flushBuffer = `-- name: FlushBuffer :one
DELETE FROM ops.buffers
WHERE id = $1
RETURNING entries
`

func (q *Queries) FlushBuffer(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, flushBuffer, id)
	var entries []byte
	err := row.Scan(&entries)
	return entries, err
}

const getBuffer = `-- name: GetBuffer :one
SELECT id, tenant_id, user_id, source, entries,
       token_count, flush_at, created_at, updated_at
FROM ops.buffers
WHERE tenant_id = $1 AND user_id = $2 AND source = $3
`

type GetBufferParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
	Source   string    `json:"source"`
}

func (q *Queries) GetBuffer(ctx context.Context, arg GetBufferParams) (OpsBuffer, error) {
	row := q.db.QueryRow(ctx, getBuffer, arg.TenantID, arg.UserID, arg.Source)
	var i OpsBuffer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Source,
		&i.Entries,
		&i.TokenCount,
		&i.FlushAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingFlush = `-- name: GetPendingFlush :many
SELECT id, tenant_id, user_id, source, entries,
       token_count, flush_at, created_at, updated_at
FROM ops.buffers
WHERE flush_at <= NOW()
`

func (q *Queries) GetPendingFlush(ctx context.Context) ([]OpsBuffer, error) {
	rows, err := q.db.Query(ctx, getPendingFlush)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpsBuffer{}
	for rows.Next() {
		var i OpsBuffer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Source,
			&i.Entries,
			&i.TokenCount,
			&i.FlushAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
