// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: edges.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getNeighbors = `-- name: GetNeighbors :many
SELECT id, tenant_id, source_memory_id, target_memory_id,
       type, weight, metadata, created_at
FROM graph.memory_edges
WHERE (source_memory_id = $1 OR target_memory_id = $1)
  AND tenant_id = $2
`

type GetNeighborsParams struct {
	SourceMemoryID uuid.UUID `json:"source_memory_id"`
	TenantID       uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetNeighbors(ctx context.Context, arg GetNeighborsParams) ([]GraphMemoryEdge, error) {
	rows, err := q.db.Query(ctx, getNeighbors, arg.SourceMemoryID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GraphMemoryEdge{}
	for rows.Next() {
		var i GraphMemoryEdge
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceMemoryID,
			&i.TargetMemoryID,
			&i.Type,
			&i.Weight,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkEdge = `-- name: LinkEdge :exec
INSERT INTO graph.memory_edges (
    id, tenant_id, source_memory_id, target_memory_id,
    type, weight, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type LinkEdgeParams struct {
	ID             uuid.UUID     `json:"id"`
	TenantID       uuid.UUID     `json:"tenant_id"`
	SourceMemoryID uuid.UUID     `json:"source_memory_id"`
	TargetMemoryID uuid.UUID     `json:"target_memory_id"`
	Type           string        `json:"type"`
	Weight         pgtype.Float4 `json:"weight"`
	Metadata       []byte        `json:"metadata"`
}

func (q *Queries) LinkEdge(ctx context.Context, arg LinkEdgeParams) error {
	_, err := q.db.Exec(ctx, linkEdge,
		arg.ID,
		arg.TenantID,
		arg.SourceMemoryID,
		arg.TargetMemoryID,
		arg.Type,
		arg.Weight,
		arg.Metadata,
	)
	return err
}
