// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entities.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const findEntitiesByName = `-- name: FindEntitiesByName :many
SELECT id, tenant_id, memory_id, name, type,
       confidence, aliases, created_at
FROM graph.extracted_entity
WHERE name ILIKE $1
`

func (q *Queries) FindEntitiesByName(ctx context.Context, name string) ([]GraphExtractedEntity, error) {
	rows, err := q.db.Query(ctx, findEntitiesByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GraphExtractedEntity{}
	for rows.Next() {
		var i GraphExtractedEntity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MemoryID,
			&i.Name,
			&i.Type,
			&i.Confidence,
			&i.Aliases,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntitiesByMemory = `-- name: GetEntitiesByMemory :many
SELECT id, tenant_id, memory_id, name, type,
       confidence, aliases, created_at
FROM graph.extracted_entity
WHERE memory_id = $1
`

func (q *Queries) GetEntitiesByMemory(ctx context.Context, memoryID uuid.UUID) ([]GraphExtractedEntity, error) {
	rows, err := q.db.Query(ctx, getEntitiesByMemory, memoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GraphExtractedEntity{}
	for rows.Next() {
		var i GraphExtractedEntity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MemoryID,
			&i.Name,
			&i.Type,
			&i.Confidence,
			&i.Aliases,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storeEntity = `-- name: StoreEntity :exec
INSERT INTO graph.extracted_entity (
    id, tenant_id, memory_id, name, type, confidence, aliases
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type StoreEntityParams struct {
	ID         uuid.UUID `json:"id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	MemoryID   uuid.UUID `json:"memory_id"`
	Name       string    `json:"name"`
	Type       string    `json:"type"`
	Confidence float32   `json:"confidence"`
	Aliases    []string  `json:"aliases"`
}

func (q *Queries) StoreEntity(ctx context.Context, arg StoreEntityParams) error {
	_, err := q.db.Exec(ctx, storeEntity,
		arg.ID,
		arg.TenantID,
		arg.MemoryID,
		arg.Name,
		arg.Type,
		arg.Confidence,
		arg.Aliases,
	)
	return err
}
