// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeJob = `-- name: CompleteJob :exec
UPDATE ops.ingestion_jobs
SET status = 'completed', completed_at = NOW(), metadata = jsonb_set(metadata, '{memory_ids}', $2::jsonb)
WHERE id = $1
`

type CompleteJobParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 []byte    `json:"column_2"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) error {
	_, err := q.db.Exec(ctx, completeJob, arg.ID, arg.Column2)
	return err
}

const createJob = `-- name: CreateJob :exec
INSERT INTO ops.ingestion_jobs (
    id, tenant_id, memory_id, status, stage, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateJobParams struct {
	ID       uuid.UUID   `json:"id"`
	TenantID uuid.UUID   `json:"tenant_id"`
	MemoryID pgtype.UUID `json:"memory_id"`
	Status   string      `json:"status"`
	Stage    string      `json:"stage"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.Exec(ctx, createJob,
		arg.ID,
		arg.TenantID,
		arg.MemoryID,
		arg.Status,
		arg.Stage,
		arg.Metadata,
	)
	return err
}

const failJob = `-- name: FailJob :exec
UPDATE ops.ingestion_jobs
SET status = 'failed', error = $2
WHERE id = $1
`

type FailJobParams struct {
	ID    uuid.UUID   `json:"id"`
	Error pgtype.Text `json:"error"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.Exec(ctx, failJob, arg.ID, arg.Error)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, tenant_id, memory_id, status, stage,
       error, metadata, created_at, updated_at, completed_at
FROM ops.ingestion_jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (OpsIngestionJob, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i OpsIngestionJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MemoryID,
		&i.Status,
		&i.Stage,
		&i.Error,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE ops.ingestion_jobs
SET status = $2, stage = $3
WHERE id = $1
`

type UpdateJobStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
	Stage  string    `json:"stage"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobStatus, arg.ID, arg.Status, arg.Stage)
	return err
}
