// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memory.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const deleteMemory = `-- name: DeleteMemory :exec
UPDATE init.memory
SET deleted_at = NOW(), deleted_by = $3
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type DeleteMemoryParams struct {
	ID        uuid.UUID   `json:"id"`
	TenantID  uuid.UUID   `json:"tenant_id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) DeleteMemory(ctx context.Context, arg DeleteMemoryParams) error {
	_, err := q.db.Exec(ctx, deleteMemory, arg.ID, arg.TenantID, arg.DeletedBy)
	return err
}

const getByContentHash = `-- name: GetByContentHash :one
SELECT id, tenant_id, user_id, source, context_id,
       type, content, content_hash, content_type,
       language, scope, decay_rate, access_count,
       deleted_by, embedding, importance, embedding_model,
       metadata, created_at, last_accessed_at, deleted_at
FROM init.memory
WHERE content_hash = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type GetByContentHashParams struct {
	ContentHash string    `json:"content_hash"`
	TenantID    uuid.UUID `json:"tenant_id"`
}

type GetByContentHashRow struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Source         string             `json:"source"`
	ContextID      string             `json:"context_id"`
	Type           string             `json:"type"`
	Content        string             `json:"content"`
	ContentHash    string             `json:"content_hash"`
	ContentType    string             `json:"content_type"`
	Language       pgtype.Text        `json:"language"`
	Scope          pgtype.Text        `json:"scope"`
	DecayRate      pgtype.Float4      `json:"decay_rate"`
	AccessCount    pgtype.Int4        `json:"access_count"`
	DeletedBy      pgtype.UUID        `json:"deleted_by"`
	Embedding      pgvector.Vector    `json:"embedding"`
	Importance     pgtype.Float4      `json:"importance"`
	EmbeddingModel pgtype.Text        `json:"embedding_model"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastAccessedAt pgtype.Timestamptz `json:"last_accessed_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetByContentHash(ctx context.Context, arg GetByContentHashParams) (GetByContentHashRow, error) {
	row := q.db.QueryRow(ctx, getByContentHash, arg.ContentHash, arg.TenantID)
	var i GetByContentHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Source,
		&i.ContextID,
		&i.Type,
		&i.Content,
		&i.ContentHash,
		&i.ContentType,
		&i.Language,
		&i.Scope,
		&i.DecayRate,
		&i.AccessCount,
		&i.DeletedBy,
		&i.Embedding,
		&i.Importance,
		&i.EmbeddingModel,
		&i.Metadata,
		&i.CreatedAt,
		&i.LastAccessedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMemory = `-- name: GetMemory :one
SELECT id, tenant_id, user_id, source, context_id,
       type, content, content_hash, content_type,
       language, scope, decay_rate, access_count,
       deleted_by, embedding, importance, embedding_model,
       metadata, created_at, last_accessed_at, deleted_at
FROM init.memory
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type GetMemoryParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetMemoryRow struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Source         string             `json:"source"`
	ContextID      string             `json:"context_id"`
	Type           string             `json:"type"`
	Content        string             `json:"content"`
	ContentHash    string             `json:"content_hash"`
	ContentType    string             `json:"content_type"`
	Language       pgtype.Text        `json:"language"`
	Scope          pgtype.Text        `json:"scope"`
	DecayRate      pgtype.Float4      `json:"decay_rate"`
	AccessCount    pgtype.Int4        `json:"access_count"`
	DeletedBy      pgtype.UUID        `json:"deleted_by"`
	Embedding      pgvector.Vector    `json:"embedding"`
	Importance     pgtype.Float4      `json:"importance"`
	EmbeddingModel pgtype.Text        `json:"embedding_model"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastAccessedAt pgtype.Timestamptz `json:"last_accessed_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetMemory(ctx context.Context, arg GetMemoryParams) (GetMemoryRow, error) {
	row := q.db.QueryRow(ctx, getMemory, arg.ID, arg.TenantID)
	var i GetMemoryRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Source,
		&i.ContextID,
		&i.Type,
		&i.Content,
		&i.ContentHash,
		&i.ContentType,
		&i.Language,
		&i.Scope,
		&i.DecayRate,
		&i.AccessCount,
		&i.DeletedBy,
		&i.Embedding,
		&i.Importance,
		&i.EmbeddingModel,
		&i.Metadata,
		&i.CreatedAt,
		&i.LastAccessedAt,
		&i.DeletedAt,
	)
	return i, err
}

const storeMemory = `-- name: StoreMemory :exec
INSERT INTO init.memory (
    id, tenant_id, user_id, source, context_id,
    type, content, content_hash, content_type,
    language, scope, decay_rate, embedding,
    importance, embedding_model, metadata
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13,
    $14, $15, $16
)
`

type StoreMemoryParams struct {
	ID             uuid.UUID       `json:"id"`
	TenantID       uuid.UUID       `json:"tenant_id"`
	UserID         uuid.UUID       `json:"user_id"`
	Source         string          `json:"source"`
	ContextID      string          `json:"context_id"`
	Type           string          `json:"type"`
	Content        string          `json:"content"`
	ContentHash    string          `json:"content_hash"`
	ContentType    string          `json:"content_type"`
	Language       pgtype.Text     `json:"language"`
	Scope          pgtype.Text     `json:"scope"`
	DecayRate      pgtype.Float4   `json:"decay_rate"`
	Embedding      pgvector.Vector `json:"embedding"`
	Importance     pgtype.Float4   `json:"importance"`
	EmbeddingModel pgtype.Text     `json:"embedding_model"`
	Metadata       []byte          `json:"metadata"`
}

func (q *Queries) StoreMemory(ctx context.Context, arg StoreMemoryParams) error {
	_, err := q.db.Exec(ctx, storeMemory,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Source,
		arg.ContextID,
		arg.Type,
		arg.Content,
		arg.ContentHash,
		arg.ContentType,
		arg.Language,
		arg.Scope,
		arg.DecayRate,
		arg.Embedding,
		arg.Importance,
		arg.EmbeddingModel,
		arg.Metadata,
	)
	return err
}

const updateMemory = `-- name: UpdateMemory :exec
UPDATE init.memory SET
    content = $3,
    content_hash = $4,
    content_type = $5,
    language = $6,
    scope = $7,
    importance = $8,
    access_count = $9,
    metadata = $10,
    last_accessed_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type UpdateMemoryParams struct {
	ID          uuid.UUID     `json:"id"`
	TenantID    uuid.UUID     `json:"tenant_id"`
	Content     string        `json:"content"`
	ContentHash string        `json:"content_hash"`
	ContentType string        `json:"content_type"`
	Language    pgtype.Text   `json:"language"`
	Scope       pgtype.Text   `json:"scope"`
	Importance  pgtype.Float4 `json:"importance"`
	AccessCount pgtype.Int4   `json:"access_count"`
	Metadata    []byte        `json:"metadata"`
}

func (q *Queries) UpdateMemory(ctx context.Context, arg UpdateMemoryParams) error {
	_, err := q.db.Exec(ctx, updateMemory,
		arg.ID,
		arg.TenantID,
		arg.Content,
		arg.ContentHash,
		arg.ContentType,
		arg.Language,
		arg.Scope,
		arg.Importance,
		arg.AccessCount,
		arg.Metadata,
	)
	return err
}
