// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type GraphEntityRelation struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	SourceEntityID uuid.UUID          `json:"source_entity_id"`
	TargetEntityID uuid.UUID          `json:"target_entity_id"`
	Predicate      string             `json:"predicate"`
	MemoryID       uuid.UUID          `json:"memory_id"`
	Weight         pgtype.Float4      `json:"weight"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type GraphExtractedEntity struct {
	ID         uuid.UUID          `json:"id"`
	TenantID   uuid.UUID          `json:"tenant_id"`
	MemoryID   uuid.UUID          `json:"memory_id"`
	Name       string             `json:"name"`
	Type       string             `json:"type"`
	Confidence float32            `json:"confidence"`
	Aliases    []string           `json:"aliases"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type GraphMemoryEdge struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	SourceMemoryID uuid.UUID          `json:"source_memory_id"`
	TargetMemoryID uuid.UUID          `json:"target_memory_id"`
	Type           string             `json:"type"`
	Weight         pgtype.Float4      `json:"weight"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type InitApiKey struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	Name         string             `json:"name"`
	KeyHash      string             `json:"key_hash"`
	KeyPrefix    string             `json:"key_prefix"`
	Scopes       []string           `json:"scopes"`
	RateLimitRps pgtype.Int4        `json:"rate_limit_rps"`
	IsActive     pgtype.Bool        `json:"is_active"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
}

type InitMemory struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Source         string             `json:"source"`
	ContextID      string             `json:"context_id"`
	Type           string             `json:"type"`
	Content        string             `json:"content"`
	ContentHash    string             `json:"content_hash"`
	ContentType    string             `json:"content_type"`
	Language       pgtype.Text        `json:"language"`
	Scope          pgtype.Text        `json:"scope"`
	DecayRate      pgtype.Float4      `json:"decay_rate"`
	AccessCount    pgtype.Int4        `json:"access_count"`
	DeletedBy      pgtype.UUID        `json:"deleted_by"`
	Embedding      pgvector.Vector    `json:"embedding"`
	Importance     pgtype.Float4      `json:"importance"`
	EmbeddingModel pgtype.Text        `json:"embedding_model"`
	Metadata       []byte             `json:"metadata"`
	SearchVector   interface{}        `json:"search_vector"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastAccessedAt pgtype.Timestamptz `json:"last_accessed_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type InitTenant struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type InitUser struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	Name         string             `json:"name"`
	ExternalID   string             `json:"external_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	IsActive     pgtype.Bool        `json:"is_active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	Settings     []byte             `json:"settings"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type OpsIngestionJob struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	MemoryID    pgtype.UUID        `json:"memory_id"`
	Status      string             `json:"status"`
	Stage       string             `json:"stage"`
	Error       pgtype.Text        `json:"error"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}
