// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relations.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getRelationsByEntity = `-- name: GetRelationsByEntity :many
SELECT id, tenant_id, source_entity_id, target_entity_id,
       predicate, memory_id, weight, created_at
FROM graph.entity_relations
WHERE source_entity_id = $1 OR target_entity_id = $1
`

func (q *Queries) GetRelationsByEntity(ctx context.Context, sourceEntityID uuid.UUID) ([]GraphEntityRelation, error) {
	rows, err := q.db.Query(ctx, getRelationsByEntity, sourceEntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GraphEntityRelation{}
	for rows.Next() {
		var i GraphEntityRelation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceEntityID,
			&i.TargetEntityID,
			&i.Predicate,
			&i.MemoryID,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storeRelation = `-- name: StoreRelation :exec
INSERT INTO graph.entity_relations (
    id, tenant_id, source_entity_id, target_entity_id,
    predicate, memory_id, weight
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type StoreRelationParams struct {
	ID             uuid.UUID     `json:"id"`
	TenantID       uuid.UUID     `json:"tenant_id"`
	SourceEntityID uuid.UUID     `json:"source_entity_id"`
	TargetEntityID uuid.UUID     `json:"target_entity_id"`
	Predicate      string        `json:"predicate"`
	MemoryID       uuid.UUID     `json:"memory_id"`
	Weight         pgtype.Float4 `json:"weight"`
}

func (q *Queries) StoreRelation(ctx context.Context, arg StoreRelationParams) error {
	_, err := q.db.Exec(ctx, storeRelation,
		arg.ID,
		arg.TenantID,
		arg.SourceEntityID,
		arg.TargetEntityID,
		arg.Predicate,
		arg.MemoryID,
		arg.Weight,
	)
	return err
}
