// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const keywordSearch = `-- name: KeywordSearch :many
SELECT id, tenant_id, user_id, source, context_id,
       type, content, content_hash, content_type,
       language, scope, decay_rate, access_count,
       deleted_by, embedding, importance, embedding_model,
       metadata, created_at, last_accessed_at, deleted_at,
       ts_rank(search_vector, plainto_tsquery('english', $1)) AS score
FROM init.memory
WHERE tenant_id = $2
  AND deleted_at IS NULL
  AND search_vector @@ plainto_tsquery('english', $1)
  AND (CASE WHEN $3::bool THEN user_id = $4 ELSE true END)
  AND (CASE WHEN $5::bool THEN type = ANY($6::text[]) ELSE true END)
  AND (CASE WHEN $7::bool THEN source = ANY($8::text[]) ELSE true END)
  AND (CASE WHEN $9::bool THEN content_type = ANY($10::text[]) ELSE true END)
  AND (CASE WHEN $11::bool THEN created_at >= $12 ELSE true END)
  AND (CASE WHEN $13::bool THEN created_at <= $14 ELSE true END)
ORDER BY score DESC
LIMIT $15
`

type KeywordSearchParams struct {
	Query              string             `json:"query"`
	TenantID           uuid.UUID          `json:"tenant_id"`
	FilterUser         bool               `json:"filter_user"`
	UserID             uuid.UUID          `json:"user_id"`
	FilterTypes        bool               `json:"filter_types"`
	MemoryTypes        []string           `json:"memory_types"`
	FilterSources      bool               `json:"filter_sources"`
	Sources            []string           `json:"sources"`
	FilterContentTypes bool               `json:"filter_content_types"`
	ContentTypes       []string           `json:"content_types"`
	FilterStartDate    bool               `json:"filter_start_date"`
	StartDate          pgtype.Timestamptz `json:"start_date"`
	FilterEndDate      bool               `json:"filter_end_date"`
	EndDate            pgtype.Timestamptz `json:"end_date"`
	ResultLimit        int32              `json:"result_limit"`
}

type KeywordSearchRow struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Source         string             `json:"source"`
	ContextID      string             `json:"context_id"`
	Type           string             `json:"type"`
	Content        string             `json:"content"`
	ContentHash    string             `json:"content_hash"`
	ContentType    string             `json:"content_type"`
	Language       pgtype.Text        `json:"language"`
	Scope          pgtype.Text        `json:"scope"`
	DecayRate      pgtype.Float4      `json:"decay_rate"`
	AccessCount    pgtype.Int4        `json:"access_count"`
	DeletedBy      pgtype.UUID        `json:"deleted_by"`
	Embedding      pgvector.Vector    `json:"embedding"`
	Importance     pgtype.Float4      `json:"importance"`
	EmbeddingModel pgtype.Text        `json:"embedding_model"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastAccessedAt pgtype.Timestamptz `json:"last_accessed_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	Score          float32            `json:"score"`
}

func (q *Queries) KeywordSearch(ctx context.Context, arg KeywordSearchParams) ([]KeywordSearchRow, error) {
	rows, err := q.db.Query(ctx, keywordSearch,
		arg.Query,
		arg.TenantID,
		arg.FilterUser,
		arg.UserID,
		arg.FilterTypes,
		arg.MemoryTypes,
		arg.FilterSources,
		arg.Sources,
		arg.FilterContentTypes,
		arg.ContentTypes,
		arg.FilterStartDate,
		arg.StartDate,
		arg.FilterEndDate,
		arg.EndDate,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KeywordSearchRow{}
	for rows.Next() {
		var i KeywordSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Source,
			&i.ContextID,
			&i.Type,
			&i.Content,
			&i.ContentHash,
			&i.ContentType,
			&i.Language,
			&i.Scope,
			&i.DecayRate,
			&i.AccessCount,
			&i.DeletedBy,
			&i.Embedding,
			&i.Importance,
			&i.EmbeddingModel,
			&i.Metadata,
			&i.CreatedAt,
			&i.LastAccessedAt,
			&i.DeletedAt,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const semanticSearch = `-- name: SemanticSearch :many
SELECT id, tenant_id, user_id, source, context_id,
       type, content, content_hash, content_type,
       language, scope, decay_rate, access_count,
       deleted_by, embedding, importance, embedding_model,
       metadata, created_at, last_accessed_at, deleted_at,
       1 - (embedding <=> $1::vector) AS score
FROM init.memory
WHERE tenant_id = $2
  AND deleted_at IS NULL
  AND (CASE WHEN $3::bool THEN user_id = $4 ELSE true END)
  AND (CASE WHEN $5::bool THEN type = ANY($6::text[]) ELSE true END)
  AND (CASE WHEN $7::bool THEN source = ANY($8::text[]) ELSE true END)
  AND (CASE WHEN $9::bool THEN content_type = ANY($10::text[]) ELSE true END)
  AND (CASE WHEN $11::bool THEN created_at >= $12 ELSE true END)
  AND (CASE WHEN $13::bool THEN created_at <= $14 ELSE true END)
ORDER BY embedding <=> $1::vector
LIMIT $15
`

type SemanticSearchParams struct {
	Embedding          pgvector_go.Vector `json:"embedding"`
	TenantID           uuid.UUID          `json:"tenant_id"`
	FilterUser         bool               `json:"filter_user"`
	UserID             uuid.UUID          `json:"user_id"`
	FilterTypes        bool               `json:"filter_types"`
	MemoryTypes        []string           `json:"memory_types"`
	FilterSources      bool               `json:"filter_sources"`
	Sources            []string           `json:"sources"`
	FilterContentTypes bool               `json:"filter_content_types"`
	ContentTypes       []string           `json:"content_types"`
	FilterStartDate    bool               `json:"filter_start_date"`
	StartDate          pgtype.Timestamptz `json:"start_date"`
	FilterEndDate      bool               `json:"filter_end_date"`
	EndDate            pgtype.Timestamptz `json:"end_date"`
	ResultLimit        int32              `json:"result_limit"`
}

type SemanticSearchRow struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Source         string             `json:"source"`
	ContextID      string             `json:"context_id"`
	Type           string             `json:"type"`
	Content        string             `json:"content"`
	ContentHash    string             `json:"content_hash"`
	ContentType    string             `json:"content_type"`
	Language       pgtype.Text        `json:"language"`
	Scope          pgtype.Text        `json:"scope"`
	DecayRate      pgtype.Float4      `json:"decay_rate"`
	AccessCount    pgtype.Int4        `json:"access_count"`
	DeletedBy      pgtype.UUID        `json:"deleted_by"`
	Embedding      pgvector.Vector    `json:"embedding"`
	Importance     pgtype.Float4      `json:"importance"`
	EmbeddingModel pgtype.Text        `json:"embedding_model"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastAccessedAt pgtype.Timestamptz `json:"last_accessed_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	Score          int32              `json:"score"`
}

func (q *Queries) SemanticSearch(ctx context.Context, arg SemanticSearchParams) ([]SemanticSearchRow, error) {
	rows, err := q.db.Query(ctx, semanticSearch,
		arg.Embedding,
		arg.TenantID,
		arg.FilterUser,
		arg.UserID,
		arg.FilterTypes,
		arg.MemoryTypes,
		arg.FilterSources,
		arg.Sources,
		arg.FilterContentTypes,
		arg.ContentTypes,
		arg.FilterStartDate,
		arg.StartDate,
		arg.FilterEndDate,
		arg.EndDate,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SemanticSearchRow{}
	for rows.Next() {
		var i SemanticSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Source,
			&i.ContextID,
			&i.Type,
			&i.Content,
			&i.ContentHash,
			&i.ContentType,
			&i.Language,
			&i.Scope,
			&i.DecayRate,
			&i.AccessCount,
			&i.DeletedBy,
			&i.Embedding,
			&i.Importance,
			&i.EmbeddingModel,
			&i.Metadata,
			&i.CreatedAt,
			&i.LastAccessedAt,
			&i.DeletedAt,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
